### ISSUE TITLE
write access of this repository

### ISSUE THREAD

**Issue by brian7685** [GAIA-AIDA/face-building#1]
Hi, 

Please give me the write access of this repository so I can update my code.
Thanks!

**Comment by brian7685** [comment]
I also finished a version and tested it.
Maybe we can use this one

docker pull brian271828/brian_aida:0510

**Comment by brian7685** [comment]
I have a new version which follows bobby's folder spec
docker pull brian271828/brian_aida:0511_2

**Comment by danielnapierski** [comment]
@brian7685 You should now have write access to the 3 CU repositories under GAIA-AIDA.

**Comment by brian7685** [comment]
> @brian7685 You should now have write access to the 3 CU repositories under GAIA-AIDA.

Yes, thanks!
